PROOF 2021-12-03 12:39:54,346  root  INFO: user_proof : Start
PROOF 2021-12-03 12:39:54,347  root  ERROR: user_proof : exception : 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "C:\Users\Indium Software\Documents\develop\document_proof\proof.py", line 36, in user_proof
    image = request.files['image']
  File "C:\Users\Indium Software\Documents\develop\document_proof\env\lib\site-packages\werkzeug\datastructures.py", line 377, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
PROOF 2021-12-03 12:39:54,349  root  DEBUG: user_proof : end
PROOF 2021-12-03 13:06:19,902  root  INFO: user_proof : Start
PROOF 2021-12-03 13:06:19,903  root  ERROR: user_proof : exception : 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "C:\Users\Indium Software\Documents\develop\document_proof\proof.py", line 36, in user_proof
    image = request.files['image']
  File "C:\Users\Indium Software\Documents\develop\document_proof\env\lib\site-packages\werkzeug\datastructures.py", line 377, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
PROOF 2021-12-03 13:06:19,906  root  DEBUG: user_proof : end
PROOF 2021-12-03 13:10:00,095  root  INFO: user_proof : Start
PROOF 2021-12-03 13:10:00,096  root  ERROR: user_proof : exception : 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "C:\Users\Indium Software\Documents\develop\document_proof\proof.py", line 36, in user_proof
    image = request.files['image']
  File "C:\Users\Indium Software\Documents\develop\document_proof\env\lib\site-packages\werkzeug\datastructures.py", line 377, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
PROOF 2021-12-03 13:10:00,106  root  DEBUG: user_proof : end
